version: '3.8'

services:
  app:
    build: .
    ports:
      - 80:3000
    depends_on:
      - db
    restart: always
    env_file: ./.env
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: video
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
volumes: 
  db:
