version: '3.8'

services:
  app:
    build: .
    ports:
      - 80:3000
    depends_on:
      - db
    restart: always
    env_file: ./.env
    environment:
      DB_HOST: db
  db:
    image: mysql:5.7
    ports:
      - $DB_PORT:$DB_PORT
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_SCHEMA
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
volumes: 
  db:
